image: java:8

stages:
  - test
  - build

before_script:
  - chmod +x mvn

test:
  stage: test
  script: ./mvn test

build:
  stage: build
  script: ./mvn package
  artifacts:
    paths:
      - target/trabalho5-1.0-SNAPSHOT.jar